name: fabu-lang
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '15 5,23 * * *'

jobs:
  release-worker:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      ___X_CMD_GHACTION_X: x2
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITCODE_TOKEN: ${{ secrets.GITCODE_TOKEN_SYNC }}
      QYWX_BOT_RELEASE_WEBHOOK: ${{ secrets.QYWX_BOT_RELEASE_WEBHOOK }}
      ssh_key: ${{ secrets.SSH_QIAKAI_KEY }}
      git_user: l
      git_email: l@x-cmd.com
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: |
            x ws fabu-lang || return

